### ISSUE TITLE
Suggestion for censoring words

### ISSUE THREAD

**Issue by SirArya** [NassimMansouri/Spotify-Lyrics-to-Discord-Status#2]
Hi Nassim,

Thank you for fixing the previous issue with the script, 

I was wondering if there is a possibility we can add / create a list within the script that will censor particular words that are added to it. (Ex. F***)

I am only asking this considering 90% of American and British rap songs. Otherwise majority of the world like Iran has better lyrics for their songs.

If it is not possible, then do not worry about it as I do not really care.
and again, thank you for this wonderful script.

**Comment by Graychii** [comment]
Hey, 

Thank you for reaching out

Added the option for words censorship, you'll find a txt file which you can add the words you want to be censored divided by ',' example (word_one,word_two,word_three...)

**Comment by SirArya** [comment]
Always doing the fastest updates, once again, kindly appreciated and thank you
